import express from 'express';
import cors from 'cors';
import multer from 'multer';
import axios from 'axios';
import { performance } from 'perf_hooks';

const app = express();
app.use(cors());
app.use(express.json({ limit: '200mb' }));
app.use(express.urlencoded({ extended: true, limit: '200mb' }));

// ── Request Timing Middleware ─────────────────────────────────
app.use((req, res, next) => {
  const start = performance.now();
  res.on('finish', () => {
    const end = performance.now();
    console.log(`[${req.method}] ${req.originalUrl} - ${res.statusCode} (${(end - start).toFixed(2)}ms)`);
  });
  next();
});

// Multer memory storage for optional LRC files
const upload = multer({ storage: multer.memoryStorage() });

const PORT = process.env.PORT || 4000;

// ──────────────────────────────────────────────
// Parse LRC → [[seconds, text], ...]
// ──────────────────────────────────────────────
function parseLrc(lrcContent) {
  const timeRegex = /\[(\d{2}):(\d{2})\.(\d{2,3})\]/;
  const parsed = [];
  for (let line of lrcContent.split('\n')) {
    line = line.trim();
    const match = timeRegex.exec(line);
    if (match) {
      const mins = parseInt(match[1]);
      const secs = parseInt(match[2]);
      const ms   = match[3].length === 2
        ? parseInt(match[3]) * 10
        : parseInt(match[3]);
      const total = mins * 60 + secs + ms / 1000;
      const text  = line.replace(timeRegex, '').trim();
      if (text) parsed.push([total, text]);
    }
  }
  // Sort lyrics by time stamp to be absolutely safe
  parsed.sort((a, b) => a[0] - b[0]);
  return parsed;
}

// ──────────────────────────────────────────────
// Build Python script via string concatenation
// ──────────────────────────────────────────────
function generatePythonScript(base64Audio, title, artist, parsedLyrics, duration) {
  const safeTitle  = title.replace(/\\/g, '\\\\').replace(/"/g, '\\"');
  const safeArtist = artist.replace(/\\/g, '\\\\').replace(/"/g, '\\"');
  
  // Safely construct a Python list representation of the lyrics to avoid single/double quote escaping issues
  const safeLyricsLines = (parsedLyrics || []).map(([time, text]) => {
    const safeText = text.replace(/\\/g, '\\\\').replace(/"/g, '\\"');
    return `    [${time}, "${safeText}"]`;
  });
  const lyricsPythonList = safeLyricsLines.length > 0
    ? '[\n' + safeLyricsLines.join(',\n') + '\n]'
    : '[]';

  // Split the huge base64 into 76-char chunks for readability
  const chunks = base64Audio.match(/.{1,76}/g) || [base64Audio];
  const audioLines = chunks.map(c => '    "' + c + '"').join('\n');

  const py = [
    '#!/usr/bin/env python3',
    '# -*- coding: utf-8 -*-',
    '"""',
    'LyricShell - Cyberpunk Terminal Music Player',
    'Generated by LyricShell Web App',
    'Requirements: pip install pygame rich colorama',
    '"""',
    '',
    'import base64, json, os, sys, time, tempfile',
    '',
    'try:',
    '    import pygame',
    '    from rich.console import Console, Group',
    '    from rich.panel import Panel',
    '    from rich.text import Text',
    '    from rich.live import Live',
    '    from rich.align import Align',
    '    import colorama',
    'except ImportError as e:',
    '    print(f"\\033[91m[ FATAL ] Missing dependency: {e}\\033[0m")',
    '    print("Run: \\033[96mpip install pygame rich colorama\\033[0m")',
    '    sys.exit(1)',
    '',
    'colorama.init(autoreset=True)',
    'console = Console()',
    '',
    '# ── Embedded Data ────────────────────────────────────────────────',
    'TITLE  = "' + safeTitle + '"',
    'ARTIST = "' + safeArtist + '"',
    'LYRICS = ' + lyricsPythonList,
    'DURATION = ' + duration,
    'AUDIO_B64 = (',
    audioLines,
    ')',
    '',
    '# ── Helpers ──────────────────────────────────────────────────────',
    'def make_temp_audio():',
    '    tmp = tempfile.NamedTemporaryFile(delete=False, suffix=".mp3")',
    '    tmp.write(base64.b64decode(AUDIO_B64))',
    '    tmp.close()',
    '    return tmp.name',
    '',
    'def render_ui(elapsed, total, lyrics, lyric_idx):',
    '    # Header panel',
    '    hdr = Text()',
    '    hdr.append("━" * 55 + "\\n", style="cyan")',
    '    hdr.append("  [ AUDIO ENGINE ONLINE ]  [ LYRIC STREAM ACTIVE ]\\n", style="bold cyan")',
    '    hdr.append("━" * 55, style="cyan")',
    '',
    '    # Now playing',
    '    np = Text()',
    '    np.append("\\nNOW PLAYING:\\n", style="bold magenta")',
    '    np.append(f"  {TITLE} — {ARTIST}\\n", style="bold white glow")',
    '',
    '    # Lyrics window',
    '    lrc = Text()',
    '    if lyrics:',
    '        if lyric_idx == -1:',
    '            lrc.append("   ♪  [ INSTRUMENTAL INTRO ]\\n\\n", style="dim cyan")',
    '        ',
    '        display_idx = max(0, lyric_idx)',
    '        lo = max(0, display_idx - 1)',
    '        hi = min(len(lyrics), display_idx + 4)',
    '        for i in range(lo, hi):',
    '            if i == lyric_idx:',
    '                # Spotlight bar: Padded active line with solid neon-green background',
    '                line_content = f"  ▶  {lyrics[i][1]} "',
    '                padded_content = line_content.ljust(51)',
    '                lrc.append(f"{padded_content}\\n", style="bold black on bright_green")',
    '            else:',
    '                lrc.append(f"     {lyrics[i][1]}\\n", style="dim white")',
    '    else:',
    '        lrc.append("  ♪  [LYRICS OFFLINE] No LRC file was uploaded\\n", style="dim cyan")',
    '',
    '    # Progress bar',
    '    pct   = min(elapsed / total, 1.0) if total > 0 else 0',
    '    filled = int(30 * pct)',
    '    bar   = "■" * filled + "□" * (30 - filled)',
    '    m, s  = divmod(int(elapsed), 60)',
    '    tm, ts = divmod(int(total), 60)',
    '    prog  = Text()',
    '    prog.append(f"\\n  [{bar}] {m:02d}:{s:02d} / {tm:02d}:{ts:02d}\\n", style="bold cyan")',
    '',
    '    return Panel(',
    '        Group(hdr, np, Panel(lrc, border_style="magenta", padding=(1, 2), title="[bold magenta]TERMINAL SIGNAL[/bold magenta]"), prog),',
    '        border_style="bright_blue",',
    '        title="[bold cyan]LyricShell OS v1.0.8[/bold cyan]",',
    '    )',
    '',
    '# ── Boot Sequence ────────────────────────────────────────────────',
    'def boot():',
    '    console.clear()',
    '    logs = [',
    '        ("[bold green]>[/bold green] [dim white]INITIALIZING LYRICSHELL...[/dim white]", 0.2),',
    '        ("[bold green][ SYSTEM READY ][/bold green]",         0.3),',
    '        ("[bold cyan]>[/bold cyan] [dim white]MOUNTING AUDIO DECODER INTERFACE...[/dim white]", 0.2),',
    '        ("[bold cyan][ AUDIO DECODER ONLINE ][/bold cyan]",    0.3),',
    '        ("[bold magenta]>[/bold magenta] [dim white]BOOTING LYRIC CORRELATION ENGINE...[/dim white]", 0.2),',
    '        ("[bold magenta][ LYRIC CORRELATION ACTIVE ][/bold magenta]", 0.4),',
    '        ("[bold white]>[/bold white] [dim white]DECOMPRESSING EMBEDDED MEMORY BUFFER...[/dim white]", 0.6),',
    '        ("[bold green][ BOOT SEQUENCE COMPLETE. PLAYBACK STARTING ][/bold green]", 0.5),',
    '    ]',
    '    for msg, delay in logs:',
    '        console.print(msg)',
    '        time.sleep(delay)',
    '    time.sleep(0.4)',
    '    console.clear()',
    '',
    '# ── Main ─────────────────────────────────────────────────────────',
    'def main():',
    '    audio_path = make_temp_audio()',
    '    try:',
    '        pygame.mixer.init()',
    '        pygame.mixer.music.load(audio_path)',
    '        ',
    '        # Get sound length safely with fallback since pygame Sound mp3 loader can be platform dependent',
    '        try:',
    '            total = pygame.mixer.Sound(audio_path).get_length()',
    '            if total <= 0:',
    '                total = DURATION',
    '        except Exception:',
    '            total = DURATION',
    '',
    '        boot()',
    '        pygame.mixer.music.play()',
    '        t0 = time.time()',
    '        calibrated = False',
    '        lyric_idx = -1',
    '',
    '        with Live(refresh_per_second=20, console=console, screen=True) as live:',
    '            while pygame.mixer.music.get_busy():',
    '                pos = pygame.mixer.music.get_pos()',
    '                ',
    '                # Calibrate t0 once based on first positive audio position returned by pygame.',
    '                # If get_pos() fails or returns 0/negative, we fall back to wall-clock elapsed time.',
    '                if pos > 0 and not calibrated:',
    '                    t0 = time.time() - (pos / 1000.0)',
    '                    calibrated = True',
    '                ',
    '                elapsed = time.time() - t0',
    '                ',
    '                # Find appropriate lyric index based on current playback time',
    '                new_idx = -1',
    '                for idx, (t_stamp, text) in enumerate(LYRICS):',
    '                    if elapsed >= t_stamp:',
    '                        new_idx = idx',
    '                    else:',
    '                        break',
    '                ',
    '                lyric_idx = new_idx',
    '                live.update(render_ui(elapsed, total, LYRICS, lyric_idx))',
    '                time.sleep(0.02)  # Ultra-smooth refresh rate',
    '    finally:',
    '        # Hard cleanup - always delete temp audio',
    '        try:',
    '            pygame.mixer.music.stop()',
    '            pygame.mixer.quit()',
    '        except Exception:',
    '            pass',
    '        if os.path.exists(audio_path):',
    '            os.remove(audio_path)',
    '            console.print("[dim red]>[/dim red] [dim white]SYSTEM SHUTDOWN: TEMPORARY BUFFER PURGED[/dim white]")',
    '',
    'if __name__ == "__main__":',
    '    try:',
    '        main()',
    '    except KeyboardInterrupt:',
    '        console.print("\\n[bold red][ USER INTERRUPT ][/bold red] SHUTTING DOWN...")',
    '        sys.exit(0)',
  ].join('\n');

  return py;
}

// ──────────────────────────────────────────────
// GET /api/search
// Proxy Deezer API searches to avoid CORS issues
// ──────────────────────────────────────────────
app.get('/api/search', async (req, res) => {
  try {
    const { q } = req.query;
    if (!q) {
      return res.status(400).json({ error: 'Search query is required' });
    }
    
    // 1. Try musicapi.x007.workers.dev (JioSaavn seevn engine) first
    try {
      console.log(`[WORKERS SEARCH] Querying seevn engine on musicapi.x007.workers.dev for "${q}"`);
      const response = await axios.get(`https://musicapi.x007.workers.dev/search`, {
        params: { q, searchEngine: 'seevn' },
        timeout: 8000
      });
      
      const results = response.data;
      if (results && Array.isArray(results) && results.length > 0) {
        console.log(`[WORKERS SEARCH] Success! Mapping ${results.length} results.`);
        const formatted = results.map(item => {
          const coverUrl = item.image || item.albumCover || item.thumbnail || 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=150';
          
          return {
            id: item.id || item.Id || item.ID || Math.random().toString(),
            title: item.title || item.name || 'Unknown Title',
            artist: { name: item.artist || item.singers || item.primaryArtists || 'Unknown Artist' },
            album: { cover_medium: coverUrl },
            preview: `/_/backend/api/stream?id=${item.id || item.Id || item.ID}&engine=seevn`,
            duration: item.duration ? parseInt(item.duration, 10) : 180,
            isFullTrack: true
          };
        });
        return res.json({ data: formatted });
      }
    } catch (apiErr) {
      console.error(`[WORKERS SEARCH ERROR] seevn engine failed (${apiErr.message}). Trying saavn.dev...`);
    }

    // 2. Try saavn.dev full track API next
    try {
      console.log(`[SAAVN SEARCH] Querying saavn.dev/api/search/songs for "${q}"`);
      const response = await axios.get(`https://saavn.dev/api/search/songs?query=${encodeURIComponent(q)}`, { timeout: 8000 });
      
      const results = response.data?.data?.results || response.data?.data || (Array.isArray(response.data) ? response.data : null);
      
      if (results && Array.isArray(results)) {
        console.log(`[SAAVN SEARCH] Success! Mapping ${results.length} full-length results.`);
        const formatted = results.map(item => {
          // Resolve highest quality image
          let coverUrl = 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=150';
          if (Array.isArray(item.image)) {
            const highQualityImgObj = item.image.find(img => img.quality === '500x500') || item.image[item.image.length - 1];
            coverUrl = highQualityImgObj?.link || highQualityImgObj?.url || coverUrl;
          } else if (typeof item.image === 'string') {
            coverUrl = item.image;
          }

          // Resolve highest quality download/audio URL (default to 320kbps)
          let audioUrl = '';
          if (Array.isArray(item.downloadUrl)) {
            const highQualityAudioObj = item.downloadUrl.find(d => d.quality === '320kbps') || item.downloadUrl.find(d => d.quality === '160kbps') || item.downloadUrl[item.downloadUrl.length - 1];
            audioUrl = highQualityAudioObj?.link || highQualityAudioObj?.url || '';
          } else if (typeof item.downloadUrl === 'string') {
            audioUrl = item.downloadUrl;
          }

          return {
            id: item.id || Math.random().toString(),
            title: item.name || item.title || 'Unknown Title',
            artist: { name: item.primaryArtists || item.artists || 'Unknown Artist' },
            album: { cover_medium: coverUrl },
            preview: `/_/backend/api/stream?url=${encodeURIComponent(audioUrl)}`,
            duration: item.duration ? parseInt(item.duration, 10) : 180,
            isFullTrack: true
          };
        });
        
        return res.json({ data: formatted });
      }
    } catch (apiErr) {
      console.error(`[SAAVN SEARCH ERROR] saavn.dev query failed (${apiErr.message}). Falling back to Deezer...`);
    }

    // 3. Fallback to Deezer Search API
    console.log(`[SAAVN SEARCH] Fetching search results from Deezer API for "${q}"`);
    const response = await axios.get(`https://api.deezer.com/search?q=${encodeURIComponent(q)}`, { timeout: 10000 });
    res.json(response.data);
  } catch (err) {
    console.error('[PROXY ERROR] Failed to fetch search results:', err.message);
    res.status(500).json({ error: 'Failed to fetch search results from fallback Deezer API' });
  }
});

// ──────────────────────────────────────────────
// GET /api/lyrics
// Proxy LRCLIB searches to avoid CORS issues
// ──────────────────────────────────────────────
app.get('/api/lyrics', async (req, res) => {
  try {
    const { title, artist } = req.query;
    if (!title || !artist) {
      return res.status(400).json({ error: 'Title and artist are required' });
    }
    console.log(`[PROXY LYRICS] Fetching lyrics for: "${title} - ${artist}"`);
    const response = await axios.get(`https://lrclib.net/api/get`, {
      params: {
        artist_name: artist,
        track_name: title
      },
      timeout: 10000
    });
    res.json(response.data);
  } catch (err) {
    console.error('[PROXY LYRICS ERROR] Failed to fetch lyrics:', err.message);
    res.status(404).json({ error: 'No lyrics found for this track' });
  }
});

// ──────────────────────────────────────────────
// GET /api/stream
// Proxy audio files with full range request (206) support to prevent CORS/truncation errors
// ──────────────────────────────────────────────
app.get('/api/stream', async (req, res) => {
  try {
    let { url, id, engine } = req.query;
    if (!url && !id) {
      return res.status(400).json({ error: 'Audio URL or ID is required' });
    }

    // Dynamic resolution of workers ID to direct stream URL
    if (id) {
      const targetEngine = engine || 'seevn';
      console.log(`[PROXY STREAM] Resolving workers ID "${id}" with engine "${targetEngine}"`);
      try {
        const fetchResp = await axios.get(`https://musicapi.x007.workers.dev/fetch`, {
          params: { id, searchEngine: targetEngine },
          timeout: 10000
        });
        // The worker may return the url as raw string or in an object under .url / .downloadUrl
        url = fetchResp.data?.url || fetchResp.data?.downloadUrl || (typeof fetchResp.data === 'string' ? fetchResp.data : null);
        console.log(`[PROXY STREAM] Successfully resolved workers ID to URL: ${url}`);
      } catch (fetchErr) {
        console.error(`[PROXY STREAM ERROR] Failed to resolve ID via workers API: ${fetchErr.message}`);
        return res.status(500).json({ error: 'Failed to resolve audio stream ID' });
      }
    }

    if (!url) {
      return res.status(404).json({ error: 'Audio stream URL could not be resolved' });
    }

    const headers = {
      'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
      'Referer': 'https://www.jiosaavn.com/'
    };

    if (req.headers.range) {
      headers['Range'] = req.headers.range;
    }

    console.log(`[PROXY STREAM] Fetching and piping audio chunk from: ${url.substring(0, 60)}...`);

    const response = await axios({
      method: 'get',
      url: url,
      responseType: 'stream',
      headers: headers,
      timeout: 20000
    });

    res.status(response.status);

    const copyHeaders = [
      'content-type',
      'content-length',
      'content-range',
      'accept-ranges'
    ];

    copyHeaders.forEach(h => {
      if (response.headers[h]) {
        res.setHeader(h, response.headers[h]);
      }
    });

    response.data.pipe(res);
  } catch (err) {
    console.error('[STREAM PROXY ERROR]:', err.message);
    res.status(500).json({ error: 'Failed to proxy audio stream' });
  }
});

// ──────────────────────────────────────────────
// POST /generate
// ──────────────────────────────────────────────
app.post('/generate', upload.single('lrcFile'), async (req, res) => {
  try {
    const { title, artist, previewUrl, duration } = req.body;
    const lrcFile = req.file;

    if (!title || !artist || !previewUrl) {
      return res.status(400).json({ error: 'Missing required fields' });
    }
    
    // 1. Download preview MP3 → Base64
    let targetAudioUrl = previewUrl;
    if (previewUrl.startsWith('/_/backend')) {
      targetAudioUrl = `http://localhost:${PORT}${previewUrl.replace('/_/backend', '')}`;
    } else if (previewUrl.startsWith('/')) {
      targetAudioUrl = `http://localhost:${PORT}${previewUrl}`;
    }

    console.log(`[GENERATE] Downloading audio stream from:`, targetAudioUrl);
    const audioResp = await axios.get(targetAudioUrl, { responseType: 'arraybuffer', timeout: 15000 });
    const base64Audio = Buffer.from(audioResp.data).toString('base64');

    // 2. Parse LRC
    let parsedLyrics = [];
    if (lrcFile) {
      parsedLyrics = parseLrc(lrcFile.buffer.toString('utf-8'));
    } else if (req.body.lrcContent) {
      // In case they post plain text instead of file upload
      parsedLyrics = parseLrc(req.body.lrcContent);
    } else {
      // LRCLIB automatic fetching as fallback
      console.log(`[GENERATE] Attempting to auto-fetch lyrics from LRCLIB for: "${title} - ${artist}"`);
      try {
        const lrcResp = await axios.get(`https://lrclib.net/api/get`, {
          params: {
            artist_name: artist,
            track_name: title
          },
          timeout: 6000 // fast timeout so generation isn't delayed
        });
        if (lrcResp.data && lrcResp.data.syncedLyrics) {
          console.log(`[GENERATE] Synced lyrics found on LRCLIB!`);
          parsedLyrics = parseLrc(lrcResp.data.syncedLyrics);
        } else if (lrcResp.data && lrcResp.data.plainLyrics) {
          console.log(`[GENERATE] Plain lyrics found on LRCLIB, parsing with simulated 4s intervals`);
          // If only plain lyrics exist, we can create sequential timestamps every 4 seconds
          const lines = lrcResp.data.plainLyrics.split('\n').map(l => l.trim()).filter(Boolean);
          parsedLyrics = lines.map((line, idx) => [idx * 4, line]);
        }
      } catch (err) {
        console.log(`[GENERATE] No lyrics retrieved from LRCLIB: ${err.message}`);
      }
    }
    
    // 3. Generate .py
    const pythonCode = generatePythonScript(base64Audio, title, artist, parsedLyrics, duration ? parseFloat(duration) : 180);

    // 4. Stream to browser as download
    const filename = 'lyricshell_' + title.toLowerCase().replace(/[^a-z0-9]+/g, '_') + '.py';
    res.setHeader('Content-Type', 'text/x-python');
    res.setHeader('Content-Disposition', 'attachment; filename="' + filename + '"');
    res.send(pythonCode);

  } catch (err) {
    console.error('[GENERATE ERROR]:', err);
    res.status(500).json({ error: 'Failed to generate Python file: ' + err.message });
  }
});

app.listen(PORT, () => {
  console.log('===================================================');
  console.log(`LYRICSHELL BACKEND LISTENING ON http://localhost:${PORT}`);
  console.log('===================================================');
});

export default app;
